export const SITE_TITLE = 'XENEXE'
export const SITE_DESCRIPTION = 'ここにサイトの説明を入れる'
export const AUTHOR_NAME = 'l7u7ch'
export const AUTHOR_BIO =
  'コンピュータサイエンスを専攻している大学院生です。研究の合間に，アニメを観たりブログサイトを運営しながら生きています。'
export const BLUESKY__SERVER = '.bsky.social'
export const BLUESKY_ID = 'l7u7ch'
export const GITHUB_ID = 'l7u7ch'
export const MISSKEY_SERVER = 'misskey.io'
export const MISSKEY_ID = 'l7u7ch'
